#!/usr/bin/env bash
# Regenerates test/test_manifold_geometry/golden_manifold.h from the ORIGINAL manifold
# math of commit d508f41 (before FW0 moved it into src/Core/).
#
# The original code is not retyped: the exact line ranges are cut out of
# `git show d508f41:src/Hardware/Manifold.cpp` and #included into
# capture_manifold_golden.cpp, which is compiled and run on the host.
#
# Only rerun this if you deliberately want new goldens (e.g. after a recalibration of
# purge_angle): the whole point of the file is that it does NOT follow the code.
#
# Usage (from the repo root, needs g++ and git on PATH):
#   bash tools/golden/capture_manifold_golden.sh
set -euo pipefail

REV=d508f41
ROOT="$(git rev-parse --show-toplevel)"
HERE="$ROOT/tools/golden"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

git -C "$ROOT" show "$REV:src/Hardware/Manifold.cpp" > "$WORK/orig_Manifold.cpp"
sed -n 76,89p   "$WORK/orig_Manifold.cpp" > "$WORK/slice_table_walk.inc"  # Manifold::begin() angle walk
sed -n 205,234p "$WORK/orig_Manifold.cpp" > "$WORK/slice_clock.inc"       # clock_minutes_for_slot / slot_for_clock_minutes
sed -n 500,516p "$WORK/orig_Manifold.cpp" > "$WORK/slice_scale.inc"       # scale_angle

cp "$HERE/capture_manifold_golden.cpp" "$WORK/capture.cpp"
g++ -std=gnu++11 -O0 -I "$WORK" -DCW=true  -o "$WORK/cap_cw"  "$WORK/capture.cpp"
g++ -std=gnu++11 -O0 -I "$WORK" -DCW=false -o "$WORK/cap_ccw" "$WORK/capture.cpp"
"$WORK/cap_cw"  > "$WORK/cw.txt"
"$WORK/cap_ccw" > "$WORK/ccw.txt"

OUT="$ROOT/test/test_manifold_geometry/golden_manifold.h"
{
echo "// GENERATED by tools/golden/capture_manifold_golden.sh - do not edit by hand."
echo "//"
echo "// Golden outputs of the ORIGINAL manifold math (Manifold::begin() slot-angle walk,"
echo "// clock_minutes_for_slot(), slot_for_clock_minutes(), scale_angle()) as it was in"
echo "// commit d508f41, before FW0 moved it into src/Core/. The original functions were"
echo "// compiled verbatim on the host (g++ 16.1, -O0 and -O2 gave identical results) with"
echo "// the constants of that commit: purge_angle = 342.07, angle_between_slots = 22.5,"
echo "// omitted_angle_nb = 12, PURGE_RAW_OFFSET = 8, 16 raw positions, NB_SLOT = 15."
echo "// Floats are stored as their IEEE-754 bit patterns so the tests compare bit for bit."
echo "#pragma once"
echo "#include <stdint.h>"
echo ""
echo "struct GoldenSlot { uint32_t angle_bits; int raw; };"
echo "struct GoldenScale { uint32_t in_bits; uint32_t out_bits; };"
echo ""
echo "// sterivex_angle[] / raw_slot_of_human_idx[] after Manifold::begin(): index 0 = purge."
echo "static const GoldenSlot GOLDEN_TABLE[15] = {"
sed -n '/^TABLE/,/^CLOCK_FOR/p' "$WORK/cw.txt" | grep "^  {"
echo "};"
echo ""
echo "// clock_minutes_for_slot(h) for h = -1 .. 16 (index = h + 1)."
echo "static const int GOLDEN_CLOCK_FOR_SLOT_CW[18] = {"
grep -A1 "^CLOCK_FOR_SLOT" "$WORK/cw.txt" | tail -1
echo "};"
echo "static const int GOLDEN_CLOCK_FOR_SLOT_CCW[18] = {"
grep -A1 "^CLOCK_FOR_SLOT" "$WORK/ccw.txt" | tail -1
echo "};"
echo ""
echo "// slot_for_clock_minutes(m) for m = -1 .. 60 (index = m + 1)."
echo "static const int GOLDEN_SLOT_FOR_CLOCK_CW[62] = {"
grep -A1 "^SLOT_FOR_CLOCK" "$WORK/cw.txt" | tail -1
echo "};"
echo "static const int GOLDEN_SLOT_FOR_CLOCK_CCW[62] = {"
grep -A1 "^SLOT_FOR_CLOCK" "$WORK/ccw.txt" | tail -1
echo "};"
echo ""
echo "// scale_angle(in) = out. Inputs: encoder angles built exactly like readEncoder()"
echo "// (pos * encoder_to_deg + 360 * nb_turns, turns -2..2), hand-picked edge values,"
echo "// and every table angle."
echo "static const GoldenScale GOLDEN_SCALE[] = {"
sed -n '/^SCALE/,$p' "$WORK/cw.txt" | grep "^  {"
echo "};"
} > "$OUT"

echo "wrote $OUT"
